# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_auto_20181127_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='english_title',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
