# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_auto_20181127_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.IntegerField(choices=[(1, '理学▪工学'), (2, '计算机'), (3, '教育▪语言'), (4, '文学▪艺术'), (5, '创业▪职场'), (6, '哲史▪文化'), (7, '经济▪管理'), (8, '医学▪农学'), (9, '心理学'), (10, '社会▪法律')], default=1),
        ),
    ]
