# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.IntegerField(choices=[(1, '开课中'), (2, '即将开课')], default=1),
        ),
    ]
