# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_auto_20181127_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('titleBackgroundImgage', models.ImageField(upload_to='background/%Y/%m')),
                ('bodyBackgroundImgage', models.ImageField(upload_to='background/%Y/%m')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.Keyword'),
        ),
    ]
