# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0008_auto_20181128_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='keyword',
        ),
        migrations.AddField(
            model_name='keyword',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='schoolapp.Category'),
        ),
    ]
