# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0009_auto_20181128_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类表', 'verbose_name_plural': '分类表'},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'verbose_name': '关键词表', 'verbose_name_plural': '关键词表'},
        ),
        migrations.AlterField(
            model_name='category',
            name='bodyBackgroundImgage',
            field=models.ImageField(blank=True, null=True, upload_to='background/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='category',
            name='titleBackgroundImgage',
            field=models.ImageField(blank=True, null=True, upload_to='background/%Y/%m'),
        ),
    ]
