# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0011_category_is_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='yisheng', max_length=20),
        ),
    ]
