# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 23:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0014_course_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='add_time',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
