# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-01 10:02
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0016_remove_course_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name': '章节表',
                'verbose_name_plural': '章节表',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('addr', models.CharField(blank=True, default='http://source3.uooconline.com/course349/video/%E7%A7%AF%E6%9E%81%E5%BF%83%E7%90%86%E5%AD%A6%20%E5%AE%A3%E4%BC%A0%E7%89%8720170817T.mp4', max_length=100, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.Chapter')),
            ],
            options={
                'verbose_name': '视频表',
                'verbose_name_plural': '视频表',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='introduction',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='课程详情'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.Course'),
        ),
    ]
