# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-01 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0018_auto_20181201_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='addr',
            field=models.CharField(blank=True, default='http://source3.uooconline.com/course349/video/%E7%A7%AF%E6%9E%81%E5%BF%83%E7%90%86%E5%AD%A6%20%E5%AE%A3%E4%BC%A0%E7%89%8720170817T.mp4', max_length=200, null=True),
        ),
    ]
