# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='url',
        ),
    ]
