# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_remove_banner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='position',
            field=models.IntegerField(choices=[(1, '顶部轮播图'), (2, '中部静态推广图')], default=1),
        ),
    ]
