# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0013_auto_20181129_0937'),
        ('userapp', '0004_auto_20181128_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.School'),
        ),
    ]
