# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0013_auto_20181129_0937'),
        ('userapp', '0005_studentinfo_school'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentinfotocourse',
            unique_together=set([('course', 'student', 'join_or_attention')]),
        ),
    ]
