# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_auto_20181129_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentinfotocourse',
            options={'verbose_name': '学习选课表', 'verbose_name_plural': '学习选课表'},
        ),
    ]
